
language: r
r: 4.0
sudo: true
cache: packages
warnings_are_errors: false
bioc_required: true
bioc_use_devel: false
r_packages:
  - devtools
before_install:
    - Rscript -e 'if(!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager");BiocManager::install(version = '3.12')}'
    - Rscript -e 'if(!requireNamespace("Gviz", quietly = TRUE)){BiocManager::install("Gviz"); library("Gviz")}'
